assn3.exe: main.cpp member.o vote.o menuParser.o menuFunction.o 
	g++ -o assn3.exe main.cpp member.o vote.o menuParser.o menuFunction.o

member.o: member.cpp default.h
	g++ -c member.cpp

vote.o: vote.cpp default.h
	g++ -c vote.cpp

menuParser.o: menuParser.cpp default.h
	g++ -c menuParser.cpp

menuFunction.o: menuFunction.cpp default.h
	g++ -c menuFunction.cpp

